# Generated by Django 4.0.3 on 2022-04-29 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='amoubt',
            new_name='amount',
        ),
    ]
